endpoint: http://localhost:8080
openapi: spec/oaf.json
defaultfeaturelimit: 100
maxfeaturelimit: 500
datasource:
  gpkg:
    file: example/addresses.gpkg
    fid: fid
  collections:
  - identifier: addresses
    description: INSPIRE Alternative Encoding Addresses
    links:     
    - href: https://geodata.nationaalgeoregister.nl/inspireadressen/extract/inspireadressen.zip
      hreflang: nl
      length: 1911454553
      rel: alternative
      type: application/x-compressed
      title: INSPIRE harmonized Addresses
    - href: https://geodata.nationaalgeoregister.nl/inspireadressen/extract/inspireadressen.gpkg
      rel: alternative
      type: application/geopackage+sqlite3
      title: Addresses Geopackage