package codegen

// this code is generated by go generate
// DO NOT EDIT BY HAND!

type Collection struct {
	Id          string   `json:"id"`
	ItemType    string   `json:"itemType,omitempty"`
	Links       []Link   `json:"links"`
	Title       string   `json:"title,omitempty"`
	Crs         []string `json:"crs,omitempty"`
	Description string   `json:"description,omitempty"`
	Extent      *Extent  `json:"extent,omitempty"`
}

type Collections struct {
	Collections []Collection `json:"collections"`
	Links       []Link       `json:"links"`
}

type ConfClasses struct {
	ConformsTo []string `json:"conformsTo"`
}

type Exception struct {
	Code        string `json:"code"`
	Description string `json:"description,omitempty"`
}

type Extent struct {
	Temporal interface{} `json:"temporal,omitempty"`
	Spatial  interface{} `json:"spatial,omitempty"`
}

type LandingPage struct {
	Description string `json:"description,omitempty"`
	Links       []Link `json:"links"`
	Title       string `json:"title,omitempty"`
}

type Link struct {
	Rel      string `json:"rel,omitempty"`
	Title    string `json:"title,omitempty"`
	Type     string `json:"type,omitempty"`
	Href     string `json:"href"`
	Hreflang string `json:"hreflang,omitempty"`
	Length   int64  `json:"length,omitempty"`
}
