package codegen

// this code is generated by go generate
// DO NOT EDIT BY HAND!

type CollectionInfo struct {
	Title       string   `json:"title,omitempty"`
	Crs         []string `json:"crs,omitempty"`
	Description string   `json:"description,omitempty"`
	Extent      *Extent  `json:"extent,omitempty"`
	Links       []Link   `json:"links"`
	Name        string   `json:"name"`
}

type Content struct {
	Collections []CollectionInfo `json:"collections"`
	Links       []Link           `json:"links"`
}

type Exception struct {
	Code        string `json:"code"`
	Description string `json:"description,omitempty"`
}

type Extent struct {
	Temporal []string  `json:"temporal,omitempty"`
	Trs      string    `json:"trs,omitempty"`
	Crs      string    `json:"crs,omitempty"`
	Spatial  []float64 `json:"spatial,omitempty"`
}

type FeatureGeoJSON struct {
	Id         string           `json:"id,omitempty"`
	Properties interface{}      `json:"properties"`
	Type       string           `json:"type"`
	Geometry   *GeometryGeoJSON `json:"geometry"`
}

type GeometryGeoJSON struct {
	Type string `json:"type"`
}

type Link struct {
	Type     string `json:"type,omitempty"`
	Href     string `json:"href"`
	Hreflang string `json:"hreflang,omitempty"`
	Rel      string `json:"rel,omitempty"`
}

type ReqClasses struct {
	ConformsTo []string `json:"conformsTo"`
}

type Root struct {
	Links []Link `json:"links"`
}
