package codegen

// this code is generated by go generate
// DO NOT EDIT BY HAND!

import (
   	"net/http"
   	"strings"
)

type Provider interface {
	SrsId() string
	String() string
	Provide() (interface{}, error)
	ContentType() string
}

type Providers interface {
    Init() error
    NewGetApiProvider(r *http.Request) (Provider, error)
{{range $key, $value := .Paths}}
/*
{{.Get.Description}}
*/
    New{{upperFirst .Get.OperationID}}Provider(r *http.Request) (Provider, error)
{{end -}}
}

// generate convenient functions to retrieve path params
{{range $key, $value := .Paths}}
// {{upperFirst .Get.OperationID}}
{{ cf $key .Get}}
{{end}}
