package codegen

// this code is generated by go generate
// DO NOT EDIT BY HAND!

import (
   	"net/http"
   	"strings"
)

const (
	JSONContentType = "application/json"
	HTMLContentType = "text/html"
)

// These are the MIME types that the handlers support.
var SupportedContentTypes []string = []string{JSONContentType,}

type Provider interface {
    Provide() (interface{}, error)
    MarshalJSON(interface{}) ([]byte, error)
    MarshalHTML(interface{}) ([]byte, error)
}

type Providers interface {
    Init() error
{{range $key, $value := .Paths}}
    New{{upperFirst .Get.OperationID}}Provider(r *http.Request) (Provider, error)
{{end -}}
}

// generate convenient functions to retrieve path params
{{range $key, $value := .Paths}}
// {{upperFirst .Get.OperationID}}
{{ cf $key .Get}}
{{end}}
