package server

// this code is generated by go generate
// DO NOT EDIT BY HAND!
import (
	"net/http"
	"regexp"
	"sort"
	"wfs3_server/provider_common"
)

type routes []*route

type route struct {
	pattern *regexp.Regexp
	handler http.Handler
}

type RegexpHandler struct {
	Routes routes
}

func (h *RegexpHandler) Handler(pattern *regexp.Regexp, handler http.Handler) {
	h.Routes = append(h.Routes, &route{pattern, handler})
	sort.Sort(sort.Reverse(h.Routes))
}

func (h *RegexpHandler) HandleFunc(pattern *regexp.Regexp, handler func(http.ResponseWriter, *http.Request)) {
	h.Routes = append(h.Routes, &route{pattern, http.HandlerFunc(handler)})
	sort.Sort(sort.Reverse(h.Routes))
}

func (h *RegexpHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	for _, route := range h.Routes {
		if route.pattern.MatchString(r.URL.Path) {
			route.handler.ServeHTTP(w, r)
			return
		}
	}
	// no pattern matched; send 404 response
	http.NotFound(w, r)
}

func (s routes) Len() int {
	return len(s)
}
func (s routes) Swap(i, j int) {
	s[i], s[j] = s[j], s[i]
}
func (s routes) Less(i, j int) bool {
	return len(s[i].pattern.String()) < len(s[j].pattern.String())
}

func (server *Server) Router() *RegexpHandler {
	router:= &RegexpHandler{}
	router.HandleFunc(regexp.MustCompile("/api"), server.HandleForProvider(provider_common.NewGetApiProvider(server.ServiceSpecPath)))
    {{range $key, $value := .Paths}}// path: {{$key}}
    router.HandleFunc(regexp.MustCompile("{{pathparams $key}}"), server.HandleForProvider(server.Providers.New{{upperFirst .Get.OperationID}}Provider))
	{{end -}}
    return router
}